LAST_DATE = '01/01/2026'
PROMPT_GUIDE = 'Please research distinct new government-healthcare items published after [LAST_DATE] that fit [TOPIC]. Treat each worthwhile source-backed item as a separate future website post. Prefer legislation, agency material, court documents, public data, peer-reviewed research, and direct institutional sources.'


WEBSITE_TOPICS = [
    {
        'Topic': 'Access',
        'Prompt': '[PROMPT_GUIDE]. Focus on availability, equity, rural care, and barriers to treatment.',
        'LastDate': '09/14/2026',
        'description': 'Availability, equity, rural care, and barriers to obtaining treatment.',
        'question': 'Who can obtain care, and where are the gaps?',
        'query': 'healthcare access equity rural care government',
        'accent': 'teal',
    },
    {
        'Topic': 'Cost',
        'Prompt': '[PROMPT_GUIDE]. Focus on prices, spending, affordability, and payment reform.',
        'LastDate': '09/14/2026',
        'description': 'Prices, public spending, affordability, and healthcare payment reform.',
        'question': 'What drives healthcare cost, and who bears it?',
        'query': 'healthcare cost affordability spending government',
        'accent': 'gold',
    },
    {
        'Topic': 'Coverage',
        'Prompt': '[PROMPT_GUIDE]. Focus on insurance markets, eligibility, enrollment, and benefits.',
        'LastDate': '09/14/2026',
        'description': 'Insurance markets, eligibility, enrollment, benefits, and coverage gaps.',
        'question': 'How are public decisions changing health coverage?',
        'query': 'health insurance coverage eligibility enrollment government',
        'accent': 'navy',
    },
    {
        'Topic': 'Public Programs',
        'Prompt': '[PROMPT_GUIDE]. Focus on Medicare, Medicaid, VA care, public health, and government delivery.',
        'LastDate': '09/14/2026',
        'description': 'Medicare, Medicaid, veterans care, public health, and government delivery systems.',
        'question': 'How are public healthcare programs changing?',
        'query': 'Medicare Medicaid VA public health government program',
        'accent': 'green',
    },
    {
        'Topic': 'Law',
        'Prompt': '[PROMPT_GUIDE]. Focus on court rulings, regulation, enforcement, and patient rights.',
        'LastDate': '09/14/2026',
        'description': 'Court rulings, regulation, enforcement, liability, and patient rights.',
        'question': 'Where do healthcare systems, public authority, and individual rights meet in law?',
        'query': 'healthcare law court regulation patient rights government',
        'accent': 'steel',
    },
    {
        'Topic': 'Legislation',
        'Prompt': '[PROMPT_GUIDE]. Focus on proposed and enacted federal, state, and local measures.',
        'LastDate': '09/14/2026',
        'description': 'Proposed and enacted healthcare measures at every level of government.',
        'question': 'Which healthcare changes are lawmakers considering or enacting?',
        'query': 'healthcare legislation bill federal state government',
        'accent': 'crimson',
    },
    {
        'Topic': 'Politics',
        'Prompt': '[PROMPT_GUIDE]. Focus on elections, executive action, parties, agencies, and public opinion.',
        'LastDate': '09/14/2026',
        'description': 'Elections, executive action, agencies, parties, and political conflict around healthcare.',
        'question': 'How is healthcare shaping political power and public debate?',
        'query': 'healthcare politics executive election agency government',
        'accent': 'red',
    },
    {
        'Topic': 'Privacy',
        'Prompt': '[PROMPT_GUIDE]. Focus on health data, surveillance, cybersecurity, consent, and digital systems.',
        'LastDate': '09/14/2026',
        'description': 'Health data, surveillance, cybersecurity, consent, and digital-care systems.',
        'question': 'Who controls sensitive health information, and how is it protected?',
        'query': 'health data privacy cybersecurity surveillance government',
        'accent': 'amber',
    },
    {
        'Topic': 'Ethics',
        'Prompt': '[PROMPT_GUIDE]. Focus on allocation, consent, discrimination, public duty, and institutional accountability.',
        'LastDate': '09/14/2026',
        'description': 'Allocation, consent, discrimination, public duty, and institutional accountability.',
        'question': 'Which values should govern healthcare policy and delivery?',
        'query': 'healthcare ethics allocation consent discrimination government',
        'accent': 'stone',
    },
]
