LAST_DATE = '03/20/2026'
PROMPT_GUIDE = 'Please research distinct new gun-control and firearms-policy items published after [LAST_DATE] that fit [TOPIC]. Treat each worthwhile source-backed item as a separate future website post. Prefer primary sources, enacted text, court material, research, and direct organizational statements.'


WEBSITE_TOPICS = [
    {
        'Topic': 'Amendments',
        'Prompt': '[PROMPT_GUIDE]. Focus on the Second Amendment, constitutional interpretation, and rights analysis.',
        'LastDate': '09/14/2026',
        'description': 'Constitutional amendments, the Second Amendment, and competing interpretations of firearms rights.',
        'question': 'How are constitutional rights being interpreted as firearms law changes?',
        'query': 'Second Amendment firearms constitutional rights court government',
        'accent': 'navy',
    },
    {
        'Topic': 'Politics',
        'Prompt': '[PROMPT_GUIDE]. Focus on elections, executive action, public officials, parties, and political conflict.',
        'LastDate': '09/14/2026',
        'description': 'Elections, executive action, public officials, parties, and political conflict around firearms.',
        'question': 'How is firearms policy shaping political power and public debate?',
        'query': 'gun control firearms politics executive election government',
        'accent': 'red',
    },
    {
        'Topic': 'Religion',
        'Prompt': '[PROMPT_GUIDE]. Focus on faith-based advocacy and moral teaching about guns and violence.',
        'LastDate': '09/14/2026',
        'description': 'Faith-based arguments, religious advocacy, and moral teaching about guns and violence.',
        'question': 'How are faith communities responding to firearms and gun violence?',
        'query': 'religion faith gun control firearms violence advocacy',
        'accent': 'gold',
    },
    {
        'Topic': 'Law',
        'Prompt': '[PROMPT_GUIDE]. Focus on court rulings, enforcement, liability, and legal doctrine.',
        'LastDate': '09/14/2026',
        'description': 'Court rulings, enforcement, liability, legal doctrine, and the operation of firearms law.',
        'question': 'Where do firearms rules, individual rights, and public safety meet in law?',
        'query': 'firearms gun control law court ruling enforcement government',
        'accent': 'steel',
    },
    {
        'Topic': 'Legislation',
        'Prompt': '[PROMPT_GUIDE]. Focus on federal, state, and local bills and enacted measures.',
        'LastDate': '09/14/2026',
        'description': 'Federal, state, and local bills and enacted measures governing firearms.',
        'question': 'Which firearms measures are lawmakers proposing or enacting?',
        'query': 'gun control firearms legislation bill federal state local',
        'accent': 'crimson',
    },
    {
        'Topic': 'Opinion',
        'Prompt': '[PROMPT_GUIDE]. Focus on substantial arguments and competing public perspectives.',
        'LastDate': '09/14/2026',
        'description': 'Arguments, commentary, and competing public perspectives on guns and regulation.',
        'question': 'Which values and assumptions drive the firearms debate?',
        'query': 'gun control firearms opinion commentary public debate',
        'accent': 'stone',
    },
    {
        'Topic': 'Activism',
        'Prompt': '[PROMPT_GUIDE]. Focus on organizations, campaigns, protests, and public action.',
        'LastDate': '09/14/2026',
        'description': 'Advocacy organizations, campaigns, protests, and public action around firearms policy.',
        'question': 'Who is organizing around gun policy, and what changes do they seek?',
        'query': 'gun control firearms activism advocacy campaign protest',
        'accent': 'green',
    },
    {
        'Topic': 'Ethics',
        'Prompt': '[PROMPT_GUIDE]. Focus on moral responsibility, safety, rights, and harm.',
        'LastDate': '09/14/2026',
        'description': 'Moral responsibility, safety, rights, harm, and ethical questions raised by firearms.',
        'question': 'What ethical duties should guide firearms ownership and policy?',
        'query': 'gun control firearms ethics morality public safety rights',
        'accent': 'teal',
    },
    {
        'Topic': 'Culture',
        'Prompt': '[PROMPT_GUIDE]. Focus on media, history, identity, recreation, and American gun culture.',
        'LastDate': '09/14/2026',
        'description': 'Media, history, identity, recreation, and the place of firearms in American culture.',
        'question': 'How does culture shape what Americans believe about guns?',
        'query': 'guns firearms culture media history identity America',
        'accent': 'amber',
    },
]
